### ISSUE TITLE
How it run

### ISSUE THREAD

**Issue by BogdanJak** [FritzTheCat9/YoutubeLinks#52]
Hi 

Do you have any instructions on how to run your project?

Bogdan

**Comment by FritzTheCat9** [comment]
The application is still in development, but some features are working and You can run the app. The are some problems with running all the containers in docker, but You can set up it manually to make it work.
1. Download app source code.
2. Have Visual Studio downloaded to run newest blazor and .net projects (.NET 8)
3. Set multiple project startup: 
![image](https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/52e0b0c6-2b08-4d1d-8f69-54e3246691e1)
Select Api and Blazor project 
![image](https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/94abbe25-cc33-42f1-a6a9-dba47ea3b896)
4. Also You will need to setup database on docker. I user docker-compose and have it all set up. 
In YoutubeLinks.Shared/Scripts.md You have some commands and scripts to set up this project.
Use docker-compose file to set up containers but for now only database one is working properly:
cd C:\Users\bartl\source\repos\YoutubeLinks
docker compose up --build -d
docker ps
Run only database container: 
![image](https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/315263ae-c8b0-4bb5-b4cb-5d97a3f013e7)
Then create and update the database:
cd C:\Users\bartl\source\repos\YoutubeLinks\YoutubeLinks.Api
dotnet ef database update
You will need to create database inside this container:
![image](https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/d92c0179-d822-4fa6-a962-eec7c15ff968)
![image](https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/4226c0f4-122a-444e-9d46-753cf33e4003)
In YoutubeLinks.Shared/Scripts.md there is info about which credentials are used to set up the database and on which ports the applications are running:
![image](https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/fb7ec2cd-8699-4688-ba8e-91fec83374fe)
6. If database is running on the docker container and Api and Blazor project are running inside Visual Studio You can login to the app with credentials:
![image](https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/10ade53e-70c0-4f5c-85f4-415f4aeeea8e)
Admin:
Email: ytlinksapp@gmail.com
Password: Asd123!
User:
Email: ytlinksapp1@gmail.com
Password: Asd123!
7. Only register function will not work because in appsettings my appllication email is linked to send registration emails:
You can change it to use another email credentials if You want.
![image](https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/6e00d36e-5f88-4880-a897-6b37b9f9a0e5)
I will try to fix Api and Blazor docker containers and provide better setup instruction. Also database setup should be more clear and the setup instrucion. 

Sorry for this a bit messy instruction. If You have any more questions feel free to ask me.

**Comment by FritzTheCat9** [comment]
I guess i fixed Api and Blazor containers issues, there were some problems with yt-dlp library that i use.
Now You should be able to start all containers from docker-compose file no need to start them manually from Visual Studio. 

Also when using database from docker you must change connection string in appsettings.json:
![image](https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/10bd41fc-edf9-401b-b745-cf89236e815b)

Fixed issue: https://github.com/FritzTheCat9/YoutubeLinks/issues/21

Thank You for helping me to improve my project.
Also i will try to make setting database faster.

**Comment by FritzTheCat9** [comment]
Fixed issue: #58 (Database should be created and migrations applied on application start)
Updated readme. 
You should be able to run my app with one command:
docker compose up --build -d

**Comment by BogdanJak** [comment]
Cześć

 

Nie wiem jak Ty to robisz ale ja ni cholery nie potrafię uruchomić twojej aplikacji. Ciągle otrzymuję błąd „Server error” zarówno z dockerem jak i bez niego.

Masz jakiś pomysł co jest nie tak albo wersję bez dockera?

 

Bogdan

**Comment by FritzTheCat9** [comment]
Wpisujesz te dwie komendy w terminalu:
```
cd C:\Users\bartl\source\repos\YoutubeLinks
docker compose up --build -d
```
![image](https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/f7b6c40c-9e5b-4a3e-953e-bc4885cc0592)

Na docker desktop powinny być widoczne 4 odpalone kontenery:
![image](https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/46fc8f58-1f86-48f2-8f20-0ef5907dfcf2)

Pod tymi linkami są dostępne aplikacje (baza danych powinna sama się utworzyć, nic nie trzeba robić):
- C# Web API backend: http://localhost:5000
![image](https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/ba11df5b-6fe2-4d38-8534-41327133603d)
- Blazor WASM frontend: http://localhost:7000
![image](https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/e8f9ccdb-2061-4e9e-ac13-c9c8caa2f41a)
- Seq Api logs: http://localhost:8081
![image](https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/9c634e80-8528-4955-a2ec-aa5eb71aae2d)

Jak odpalam tak aplikację to wszystko mi działa.
Możesz podesłać mi jakiś zrzut ekranu? 

Server error może wystąpić jak nie działa Api:
![image](https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/3403464d-49ed-4b4c-b437-00e1d502d62b)
Jak ten kontener jest wyłączony to będzie sypało server errorami (bo Api nie jest włączone):
![image](https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/7455e1e7-1878-4e44-b51f-ddf18d58145d)
Można podejrzeć logi z kontenera (wtedy widać gdzie jest błąd lub gdzie coś się wywaliło w aplikacji):
![image](https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/8722cf34-a3bd-401f-bf07-b8c471fe5b89)

**Comment by FritzTheCat9** [comment]
Sposób na odpalenie aplikacji bez dockera:

- Ustawiamy aplikacje które mają startować (wybieramy w Api http i Blazor http, potem zaznaczamy je jako multiple project startup).

- YoutubeLinks.Api -> appsettings.json -> podmieniamy connection string na:
`"ConnectionString": "Server=(localdb)\\mssqllocaldb;Database=YoutubeLinks;Trusted_Connection=True;"`

- Na serwerze: "(localdb)\mssqllocaldb" powinna utworzyć się baza danych o nazwie YoutubeLinks (po starcie aplikacji).

- Startujemy aplikację

Filmik z podmianą connection stringa:
https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/8ca8f879-2c77-4da7-8985-c248bd8fa63e

Filmik z odpalenia apki:
https://github.com/FritzTheCat9/YoutubeLinks/assets/62745092/79f0241c-0cf6-41e0-83e7-bb9af69fa2f3

**Comment by BogdanJak** [comment]
Dzięki – bez dockera apka ruszyła bez problemu

 

Bogdan
